// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TestMaterialesAPI.Model
{
    public partial class Categoria
    {
        public int IdCategoria { get; set; }
        public string Descripcion { get; set; }
    }
}