// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TestMaterialesAPI.Model
{
    public partial class Material
    {
        public int IdMeterial { get; set; }
        public string NombreMaterial { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int IdCategoria { get; set; }
        public string Proveedor { get; set; }
        public int IdUnidadMedida { get; set; }
        public decimal Existencia { get; set; }
    }
}